### ISSUE TITLE
N *4* cause Crash

### ISSUE THREAD

**Issue by DerHirschi** [DeltaLima/TheNetNode-CB#1]
there seems to be a bug in the TNN software from version 1.79.49 (thanks to Ralph Y02HAL),
which causes TNN to crash.
"TheNetNode caused an unknown system error!!!"
"Last function was: l1tcpip(TcpipSV)"

The crash is triggered by entering the (N)ODES command with certain parameters.
As an example, N 'star'4'star' leads to the crash, but other parameters/combinations are also affected.

It is recommended to lock the N command.
Here is a solution approach, developed by Ralph(Y02HAL).

1.
Create the file fix.txt in the folder tnn/textcmd
(The content of the file is output instead of the N command when the command is called).

2.
Create aliases for all combinations of the N command.
So in the TNN console:

ALIAS N fix
ALIAS NO fix
ALIAS NOD fix
ALIAS NODE fix
ALIAS NODES fix

SP

**Comment by DeltaLima** [comment]
Thank you for the report! 

I dont know but it looks to me that you got the wrong git repo for your report, this is an archived version of TNN 1.79cb53


Actually I cannot reproduce the problem you are describing:

```
DLM274 de BLX274 (21:38)==>N 4
Berlin:BLX274> No entry for: 4
DLM274 de BLX274 (21:38)==>
DLM274 de BLX274 (21:38)==>ver
Berlin:BLX274> TheNetNode (Linux) (CB), Version 1.79cb53 (Jun 17 2019)
     Copyright by NORD><LINK, free for non-commercial usage.
         See www.nordlink.org for further information.
  This version compiled for 16 Ports, 400 L2-Links and 200 Circuits.
       *** CB-Version by DAA531, http://dig531.dyndns.org. ***
```

**Comment by DerHirschi** [comment]
```
JO52NU:CB0SAW> TheNetNode (Linux) (CB), Version 1.79cb53 (Jan 22 2021)
     Copyright by NORD><LINK, free for non-commercial usage.
         See www.nordlink.org for further information.
  This version compiled for 16 Ports, 400 L2-Links and 200 Circuits.
       *** CB-Version by DAA531, http://dig531.dyndns.org.
```

Moin,
wir konnten es bisher auch nicht überall reproduzieren. 

Es scheint auch abhängig davon zu sein wie voll die Node Liste ist.
Auch Parameter *c*, *d*, ... Sind davon betroffen.. *x* z.B. nicht mehr .. 
Es sind grade ein paar Leute dabei zu Testen und versuchen den Fehler einzugrenzen.

Ich würde neue Erkenntnisse hier aktualisieren und deshalb den Issues-Report hier erst mal solange offen halten wollen.

73, Manuel(MD2SAW)

**Comment by DerHirschi** [comment]
Here is a small update on the TNN crash and unfortunately nothing pleasant.
It seems that the "DEST" command is also affected.
The combination "D 'star'4'star'" also triggers a crash of TNN, with the same message as below. 
same message as below.

Again, it is recommended to temporarily disable the D command until a solution to the problem is found. 
problem is found.

ALIAS D fix
ALIAS DE fix
ALIAS DES fix
ALIAS DEST fix

The error occurs in 32-bit Linux versions as well as 64-bit linux versions.

------------------------------------------------------------------------------------------------------------

hier ein kleines update zum Thema TNN Crash und leider nichts erfreuliches.
Es scheint so al ob der Befehl "DEST" auch betroffen ist.
Die Kombination "D *4*" löst bei mir ebenfalls ein Crash von TNN aus, mit der 
selben Meldung wie unten.

Auch hier empfiehl sich den Befehl D vorübergehend zu sperren, bis eine Lösung für das 
Problem gefunden ist.

ALIAS D fix
ALIAS DE fix
ALIAS DES fix
ALIAS DEST fix

Der Fehler tritt in 32-bit Linux Versionen sowie 64-bit linux Versionen auf.

**Comment by DerHirschi** [comment]
Sry ..
Combination 
N 'star'4'star'
and 
D 'star'4'star' 

and other Parameter with 'star' Wildcards
'star' is not shown here. for whatever reason

**Comment by DerHirschi** [comment]
Danke Ralph(Y02HAL) und Peter(PE1FTL) wurde das Problem denke ich lokalisiert.

Das Problem tritt erst ab Version xx49 auf.
In der Datei /src/callstr.c wurde Zeile 418 verändert von Version 48 zu 49.

Version 49:
 if (strlen(*n) >= 1)
 
 Version 48:
 if (n[-1] != *a)
 
Also 
    /src/callstr.c  Zeile 418
 von 
    if (strlen(*n) >= 1)
 auf
    if (n[-1] != *a)
 ändern.
 Wir haben die Änderung jetzt auf verschiedenen Systemen getestet und bisher laufen die Kisten ohne Probleme.
 
 Es wäre nett, wenn nach Bestätigung ein update erfolgen würde.
 
 
 
 73,
 Manuel

**Comment by DeltaLima** [comment]
Danke für die Info! Das Problem kann ich mit `*4*` nachvollziehen und werde dann auch den von dir gestellten patch einspielen und testen und dann in den master pushen :)
